name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2
        
      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Navigate to the correct directory (if package.json is inside a folder, e.g., 'app')
      - name: Change directory to app
        run: cd app  # Adjust this if the directory name is different

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Run tests
      - name: Run tests
        run: npm test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Step 3: Navigate to the correct directory for deployment (if required)
      - name: Change directory to app
        run: cd app  # Adjust as needed

      # Step 4: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 5: Deploy (this is an example, adjust as per your deployment method)
      - name: Deploy to Production
        run: |
          ssh user@your-server "cd /path/to/your/project && git pull origin main && npm install && pm2 restart your-app"
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.HOST }}
          USER: ${{ secrets.USER }}
